# Generated by Django 3.0.4 on 2020-03-12 14:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('count_page', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comcost',
            name='date',
            field=models.DateField(default=datetime.date(2020, 3, 12)),
        ),
    ]
