# Generated by Django 3.0.4 on 2020-03-12 14:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('count_page', '0002_auto_20200312_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comcost',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 3, 12, 17, 41, 27, 649800)),
        ),
    ]
