# Generated by Django 3.0.4 on 2020-03-12 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('count_page', '0002_auto_20200312_1454'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComCost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('electric_cost', models.CharField(default='', max_length=256)),
                ('water_h_cost', models.CharField(default='', max_length=256)),
                ('water_c_cost', models.CharField(default='', max_length=256)),
                ('waste_cost', models.CharField(default='', max_length=256)),
            ],
        ),
    ]
