# Generated by Django 3.0.4 on 2020-04-15 09:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('count_page', '0003_auto_20200312_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='comcost',
            name='last_bill',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='comcost',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 4, 15, 12, 58, 36, 715398)),
        ),
    ]
