# Generated by Django 3.0.4 on 2020-04-15 10:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('count_page', '0004_auto_20200415_1258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comcost',
            name='last_bill',
        ),
        migrations.AddField(
            model_name='com',
            name='last_bill',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='comcost',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 4, 15, 13, 2, 6, 925975)),
        ),
    ]
